# Generated by Django 2.2.7 on 2019-12-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AddField(
            model_name='lead',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
