# Generated by Django 2.2.7 on 2019-12-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.CharField(max_length=700),
        ),
    ]
